id = "jsp"
name = "JSP"
description = "JSP support."
version = "0.3.2"
schema_version = 1
authors = ["Riccardo Strina <riccardo.strina@icloud.com>"]
repository = "https://github.com/tartarughina/zed-jsp"

[grammars.jsp]
repository = "https://github.com/tartarughina/tree-sitter-jsp"
commit = "b9fac3b883e2dca0ffc6a4e68196e81363465540"

[grammars.el]
repository = "https://github.com/tartarughina/tree-sitter-el"
commit = "b160fa71bad3ca94f0fdc91f6101f1c6c6812b44"
